Add experimental spec file

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -41,21 +41,40 @@ jobs:
           ls -lah
 
           [ "$GITHUB_REF" == "refs/heads/master" ] && CHANNEL=$MATTERMOST_CHANNEL || CHANNEL=$MATTERMOST_DEV_CHANNEL
-          [ "$GITHUB_REF" == "refs/heads/master" ] && FILE_NAME="liman-$VERSION-$GITHUB_RUN_NUMBER.deb" || FILE_NAME="liman-${GITHUB_REF#refs/heads/}-$VERSION-$GITHUB_RUN_NUMBER.deb"
+          [ "$GITHUB_REF" == "refs/heads/master" ] && FILE_NAME="liman-$VERSION-$GITHUB_RUN_NUMBER" || FILE_NAME="liman-${GITHUB_REF#refs/heads/}-$VERSION-$GITHUB_RUN_NUMBER"
           FILE_NAME=$(echo $FILE_NAME | tr / -)
           
-          cp package.deb $FILE_NAME
+          cp package.deb $FILE_NAME.deb
           
           post_id=$(curl --location --request POST "$MATTERMOST_URL/api/v4/files?channel_id=$CHANNEL" \
             --header "Authorization: Bearer $MATTERMOST_TOKEN" \
             --header 'Content-Type: multipart/form-data' \
-            --form "files=@$FILE_NAME" | jq -r '.file_infos[0].id')
+            --form "files=@$FILE_NAME.deb" | jq -r '.file_infos[0].id')
 
           echo $post_id
           
           echo "RELEASE_VER=$(echo $VERSION)" >> $GITHUB_ENV
-          echo "RELEASE_FILENAME=$(echo $FILE_NAME)" >> $GITHUB_ENV
+          echo "RELEASE_FILENAME=$(echo $FILE_NAME.deb)" >> $GITHUB_ENV
           echo "RELEASE_RUNNUMBER=$(echo $GITHUB_RUN_NUMBER)" >> $GITHUB_ENV
+          
+          if [ -z "$post_id" ]; then
+              echo "Failed to create post :("
+              exit 4
+          else
+              curl --location --request POST "$MATTERMOST_URL/api/v4/posts" \
+                --header "Authorization: Bearer $MATTERMOST_TOKEN" \
+                --header "Content-Type: application/json" \
+                --data "{\"file_ids\":[\"$post_id\"],\"message\":\"$MESSAGE\",\"channel_id\":\"$CHANNEL\"}"
+          fi
+
+          cp package.rpm $FILE_NAME.rpm
+          
+          post_id=$(curl --location --request POST "$MATTERMOST_URL/api/v4/files?channel_id=$CHANNEL" \
+            --header "Authorization: Bearer $MATTERMOST_TOKEN" \
+            --header 'Content-Type: multipart/form-data' \
+            --form "files=@$FILE_NAME.rpm" | jq -r '.file_infos[0].id')
+
+          echo $post_id
           
           if [ -z "$post_id" ]; then
               echo "Failed to create post :("
