Added github releases

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -52,11 +52,20 @@ jobs:
             --form "files=@$FILE_NAME" | jq -r '.file_infos[0].id')
 
           echo $post_id
-
           
           echo "RELEASE_VER=$(echo $VERSION)" >> $GITHUB_ENV
           echo "RELEASE_FILENAME=$(echo $FILE_NAME)" >> $GITHUB_ENV
           echo "RELEASE_RUNNUMBER=$(echo $GITHUB_RUN_NUMBER)" >> $GITHUB_ENV
+          
+          if [ -z "$post_id" ]; then
+              echo "Failed to create post :("
+              exit 4
+          else
+              curl --location --request POST "$MATTERMOST_URL/api/v4/posts" \
+                --header "Authorization: Bearer $MATTERMOST_TOKEN" \
+                --header "Content-Type: application/json" \
+                --data "{\"file_ids\":[\"$post_id\"],\"message\":\"$MESSAGE\",\"channel_id\":\"$CHANNEL\"}"
+          fi
 
       - name: Release 🚀
         id: create_release
